about:
  summary: RepeatMasker from UCSC
build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  number: 0
extra:
  authors: bsp
  extra-files: []
  genome-build: hg19
  keywords:
  - rmsk
  - region
  species: Homo_sapiens
package:
  name: hg19-repeatmasker
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
