build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: grcz10-reference-genome-ensembl-v1
  version: '1'
requirements:
  build:
  - samtools
  - zlib
  run:
  - samtools
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCz10
    species: Danio_rerio
  keywords:
  - ref
  - reference
  - zebrafish
  - genome
  - Ensembl
  - fasta-file
  summary: The GRCz10 release 91 reference genome from Ensembl
  tags:
    data-version: Release-91
    ggd-channel: genomics
