build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: grch37-pfam-domains-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh37
    species: Homo_sapiens
  keywords:
  - pfam
  - domains
  - protein
  - protein-domains
  - UCSC
  - bed
  - bed-file
  summary: Pfam domain annotation in bed12 format. (From UCSC) Remapped from hg19
    to GRCh37 (unmapped regions removed)
  tags:
    data-provider: UCSC
    data-version: 16-Apr-2017
    ggd-channel: genomics
