build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: u1072557
  extra-files: []
package:
  name: grch37-gnomd_sv-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh37
    species: Homo_sapiens
  keywords:
  - sv
  - gnomAD
  summary: SV callset from gnomAD
  tags:
    data-version: 20-Mar-2019
    ggd-channel: genomics
