build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: grch37-hapmap-broad-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh37
    species: Homo_sapiens
  keywords:
  - hapmap
  - broad-institute
  - vcf-file
  summary: The hapmap vcf versoin 3.3 from the broad institute
  tags:
    data-version: 3.3 - 12/7/13
    ggd-channel: genomics
