build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: grch37-esp-variants-uw-v1
  version: '1'
requirements:
  build:
  - grch37-reference-genome-1000g-v1
  - gsort
  - htslib
  - perl
  - vt
  - zlib
  run:
  - grch37-reference-genome-1000g-v1
  - gsort
  - htslib
  - perl
  - vt
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh37
    species: Homo_sapiens
  keywords:
  - ESP
  - vcf-file
  summary: 'The NHLBI Exome Sequencing Project (ESP) variants from the University of Washington.
    ESP6500SI. all snps and indels.  (More Info: http://evs.gs.washington.edu/EVS/#tabs-7)'
  tags:
    data-version: ESP6500SI-V2
    ggd-channel: genomics
