build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: hg38-gtf-ensembl-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg38
    species: Homo_sapiens
  keywords:
  - gtf
  - gtf-file
  - ensembl
  summary: The GRCh38 gtf file from ensembl remapped to hg38 (Any unmapped entries
    are removed from the file)
  tags:
    data-version: release-96
    ggd-channel: genomics
