build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: grch37-seqeunce-1000g-v1
  version: '1'
requirements:
  build:
  - htslib
  - samtools
  - zlib
  run:
  - htslib
  - samtools
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh37
    species: Homo_sapiens
  keywords:
  - seqeunce
  - 1000g
  - fasta-file
  summary: The fasta seqeunce from 1000g
  tags:
    data-version: 37 - 7/11/11
    ggd-channel: genomics
