build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: hg19-pfam-domains-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg19
    species: Homo_sapiens
  keywords:
  - pfam
  - domains
  - protein
  - protein-domains
  - UCSC
  summary: Pfam domain annotation in bed12 format. (From UCSC)
  tags:
    data-version: 16-Apr-2017
    ggd-channel: genomics
