build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 2
extra:
  authors: mjc
  extra-files: []
package:
  name: grch37-evofold-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCh37
    species: Homo_sapiens
  keywords:
  - mRNA
  - secondary-structure
  - conserved
  - evofold
  - UCSC
  - bed-file
  summary: The evolutionary conserved mRNA secondary structure predictions hosted
    on UCSC (Evofold). In bed format. (This file has been remapped from hg19 to GRCh37
    with any unmappable contigs removed)
  tags:
    data-version: 26-Dec-2010
    ggd-channel: genomics
