about:
  summary: " ClinVar: http://www.clinvar.com/\n\n \n\n UCSFify name sed magic from:\
    \ https://github.com/mmarchin/utilities/blob/master/ucscify.sh\n"
build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
extra:
  authors: bcbio
package:
  name: hg38-clinvar
  version: '20150330.2'
requirements:
  build:
  - htslib
  - zlib
  run:
  - htslib
  - zlib
# to make a pre-built package, move pre-link.sh to build.sh
# and add source and fn here
#source:
    #url: http://example.com/ex.tgz
    #fn: ex.tgz
