build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files:
  - hg38-sequence-1000g-v1.dict
package:
  name: hg38-sequence-1000g-v1
  version: '1'
requirements:
  build: []
  run: []
source:
  path: .
about:
  identifiers:
    genome-build: hg38
    species: Homo_sapiens
  keywords:
  - sequence
  - 1000g
  - fasta-file
  summary: Full hg38/GRCh38 reference genome distributed by 1000 genomes Derived from
    NCBI set with HLA and decoy alternative alleles ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/
  tags:
    data-version: 1000g - 3/8/15
    ggd-channel: genomics
