build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: yliu
  extra-files: []
package:
  name: danrer10-sequence-ucsc-v1
  version: '1'
requirements:
  build:
  - htslib
  - samtools
  - zlib
  run:
  - htslib
  - samtools
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: danRer10
    species: Danio_rerio
  keywords:
  - sequence
  - soft-masked
  summary: Soft-masked sequence from ucsc
  tags:
    data-version: 02-Sept-2014
    ggd-channel: genomics
