build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: hg38-gtf-refseq-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg38
    species: Homo_sapiens
  keywords:
  - GTF
  - ReFSeq
  - potein-coding
  - non-protein-coding
  - refGene
  - UCSC
  summary: 'The UCSC RefSeq gene track converted into GTF format containing known
    human protein-coding and non-protein-coding genes from RefSeq. (RefSeq: NCBI RNA
    reference sequence collection) (UCSC GTF format info: https://genome.ucsc.edu/FAQ/FAQformat.html#format3)'
  tags:
    data-version: 31-Mar-2019
    ggd-channel: genomics
