build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: hg38-ncbi-refseq-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg38
    species: Homo_sapiens
  keywords:
  - ncbi
  - refseq
  - UCSC
  - NCBI-RNA-reference-seqeunce-collection
  - bed-file
  summary: The composite NCBI RefSeq gene track from UCSC converted to bed format.
    (Human protein-coding and non-protein-coding genes from NCBI RefSeq)
  tags:
    data-version: 03-Mar-2019
    ggd-channel: genomics
