build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 2
extra:
  authors: mjc
  extra-files: []
package:
  name: hg38-reference-genome-ucsc
  version: '1'
requirements:
  build:
  - samtools
  - zlib
  run:
  - samtools
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg38
    species: Homo_sapiens
  keywords:
  - ref
  - reference
  - genome
  - UCSC
  summary: The hg38 reference genome from UCSC. This version includes the latest patch,
    patch 12. (url:http://hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/p12/)
  tags:
    data-version: 10-Aug-2018
    ggd-channel: genomics
