build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: yliu
  extra-files: []
package:
  name: grcz10-sequence-ensembl-v1
  version: '1'
requirements:
  build:
  - htslib
  - samtools
  - zlib
  run:
  - htslib
  - samtools
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: GRCz10
    species: Danio_rerio
  keywords:
  - sequence
  summary: Sequence from ensembl
  tags:
    data-version: GCA_000002035.3
    ggd-channel: genomics
