build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  noarch: generic
  number: 0
extra:
  authors: mjc
  extra-files: []
package:
  name: hg38-segmental-dups-ucsc-v1
  version: '1'
requirements:
  build:
  - gsort
  - htslib
  - zlib
  run:
  - gsort
  - htslib
  - zlib
source:
  path: .
about:
  identifiers:
    genome-build: hg38
    species: Homo_sapiens
  keywords:
  - superdups
  - segdups
  - seg
  - dups
  - duplications
  - UCSC
  - bed-file
  summary: The hg38 segmental duplications (SuperDups) file from UCSC. That is, duplications
    of at least 1kb total sequence of non-repeatmasker sequence in bed format
  tags:
    data-version: 19-Oct-2014
    ggd-channel: genomics
